### ISSUE TITLE
the latest code in master was not released

### ISSUE THREAD

**Issue by singuliere** [PavanTatikonda/itypes#12]
Would it be possible to publish a release and push it it to pypi? The [1.1.0 release](https://pypi.org/project/itypes//1.1.0/) is from 2016 and does not contain [the python 3 clasifiers](https://github.com/tomchristie/itypes/commit/1c1ee6adc83a198615a50eac2651d190ceb66132) added in 2017.

**Comment by tomchristie** [comment]
Sory going to punt this repo into read-only mode. Got other things I need to focus on.

**Comment by PavanTatikonda** [comment]
@singuliere  Took the transfer of this repo from Tom and released 1.2.0 to PyPI ```https://pypi.org/project/itypes/1.2.0/#files```
